# This is our production compose file - not changed for docker-sync or similar

version: "3"
services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    restart: always
    volumes:
      - pgdata:/pgdata
    ports:
      - 5432:5432
    environment:
      - PGDATA=/pgdata
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
  www:
    build:
      context: .
      dockerfile: dockerfile-www
    volumes:
      - bundle:/usr/local/bundle
      - ./app:/app
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - RACK_ENV
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
      - OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET
      - OAUTH2_CLIENT_REDIRECT_URI
      - OAUTH2_PROVIDER
      - LDAP_ADMIN_GROUP
    ports:
      - 9292:9292
    links:
      - db
    command: ./docker-command
volumes:
  bundle:
  pgdata:
