# This is our production compose file - not changed for docker-sync or similar

version: "3"
services:
  db:
    build:
      context: .
      dockerfile: dockerfile-db
    restart: always
    volumes:
      - ./pgdata:/pgdata
    environment:
      - PGDATA=/pgdata
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
  www:
    build:
      context: .
      dockerfile: dockerfile-www
    volumes:
      - ./bundle:/usr/local/bundle
    environment:
      - BUNDLE_PATH=/usr/local/bundle
      - GEM_HOME=/usr/local/bundle
      - RACK_ENV
      - CHURN_USER
      - CHURN_PASS
      - PGDATESTYLE
    ports:
      - 9292:9292
    links:
      - db
    command: ./docker-command
