application_start_date: 2011-8-14
use_new_query_generation_method: true
work_site_dimension_id: companyid
default_groupby_dimension_id: branchid
member_paying_status_code: 1
member_awaiting_first_payment_status_code: 14
member_stopped_paying_status_code: 11
dimensions:
  - id: branchid
    name: Branch
  - id: industryid
    name: Industry
  - id: lead
    name: Lead Organiser
  - id: org
    name: Organiser
  - id: areaid
    name: Area
  - id: companyid
    name: Work Site
  - id: agreementexpiry
    name: Agreement Expiry
  - id: del
    name: Delegate Training
    roles: none
  - id: hsr
    name: HSR Training
    roles: none
  - id: gender
    name: Gender
  - id: feegroupid
    name: Fee Group
  - id: state
    name: State
  - id: nuwelectorate
    name: Electorate
  - id: statusstaffid
    name: Data Entry
    roles: lead
  - id: supportstaffid
    name: Support Staff
  - id: employerid
    name: Employer
  - id: hostemployerid
    name: Owner
    roles: lead
  - id: employmenttypeid
    name: Employment Type
  - id: paymenttypeid
    name: Payment Type
  - id: last_site_training_type
    name: Last Course Category
    roles: trainer
  - id: last_site_training
    name: Last Course
    roles: trainer
  - id: last_site_training_age
    name: Training Age
    roles: trainer
  - id: last_site_trainer
    name: Trainer
    roles: trainer
  - id: last_site_training_venue
    name:  Training Venue
    roles: trainer
drilldown_order:
  branchid: lead
  industryid: companyid
  lead: org 
  org: companyid
  areaid: companyid 
  companyid: companyid
  del: companyid
  hsr: companyid 
  feegroupid: companyid
  state: areaid
  nuwelectorate: org
  statusstaffid: companyid
  supportstaffid: org
  employerid: companyid
  hostemployerid: companyid
  employmenttypeid: companyid
  paymenttypeid: paymenttypeid
summary_data_tables:
    summary:
        display_name: Summary
        query_columns:
            - row_header
            - row_header1
            - period_header
            - a1p_real_gain
            - a1p_to_other
            - paying_start_count
            - paying_real_gain
            - paying_real_loss
            - paying_end_count
            - paying_real_net
            - running_paying_net
    summary_leader:
        display_name: Summary
        query_columns:
            - row_header
            - row_header1
            - period_header
            - a1p_real_gain
            - a1p_to_other
            - paying_start_count
            - paying_real_gain
            - paying_real_loss
            - paying_end_count
            - paying_real_net
            - running_paying_net
            - contributors
            - income_net
            - annualisedavgcontribution
    paying:
        display_name: Paying
        query_columns:
            - row_header
            - row_header1
            - period_header
            - paying_start_count
            - paying_real_gain
            - paying_real_loss
            - paying_other_gain
            - paying_other_loss
            - paying_end_count
            - paying_real_net
    a1p:
        display_name: New Applications
        query_columns:
            - row_header
            - row_header1
            - period_header
            - a1p_start_count
            - a1p_real_gain
            - a1p_to_paying
            - a1p_to_other
            - a1p_other_gain
            - a1p_other_loss
            - a1p_end_count
            - a1p_net
            - a1p_newjoin
            - a1p_rejoin
            - a1p_unchanged_gain
    stopped:
        display_name: Stopped Paying
        query_columns:
          - row_header 
          - row_header1 
          - period_header
          - stopped_start_count
          - stopped_real_gain
          - stopped_to_other
          - stopped_to_paying
          - stopped_other_gain
          - stopped_other_loss
          - stopped_end_count
          - stopped_unchanged_gain
detail_data_tables:
    member_summary:
        display_name: Member Summary
        query_columns:
            - row_header
            - row_header1
            - row_header2
            - changedate
            - member
            - oldstatus
            - newstatus
            - currentstatus
            - oldcompanyid
            - newcompanyid
            - currentcompanyid
    organiser:
        display_name: Organiser
        query_columns:
            - row_header
            - row_header1
            - row_header2
            - changedate
            - member
            - oldorg
            - neworg
            - currentorg
            - oldlead
            - newlead
            - currentlead
    financial:
        display_name: Financial
        query_columns:
            - row_header
            - row_header1
            - row_header2
            - member
            - posted
            - unposted
roles:
    lead:
        password: growth
        show_transactions: true
        show_target_calculation: true
        summary_data_tables:
            - summary_leader
            - paying
            - a1p
            - stopped
        detail_data_tables:
            - member_summary
            - organiser
            - financial
    staff:
        password: followup
        show_transactions: true
        show_target_calculation: true
        summary_data_tables:
            - summary_leader
            - paying
            - a1p
            - stopped
        detail_data_tables:
            - member_summary
            - organiser
            - financial
    user:
        show_target_calculation: true
        summary_data_tables:
            - summary
            - paying
            - a1p
            - stopped
        detail_data_tables:
            - member_summary
            - organiser
    trainer:
        password: gogogo
        show_target_calculation: true
        summary_data_tables:
            - summary
            - paying
            - a1p
            - stopped
        detail_data_tables:
            - member_summary
            - organiser
column_names:
  a1p_real_gain: new applications (total)
  a1p_to_other: applications failed
  a1p_to_other: applications exited w/out payment
  paying_start_count: paying at start date
  paying_real_gain: started paying
  paying_real_loss: ceased paying
  a1p_start_count: applications pending payment at start
  a1p_end_count: applications pending payment at end
  paying_real_net: paying net
  paying_end_count: paying at end date
  posted: income posted
  unposted: income corrections
  income_net: income net
  running_paying_net: paying net (running total)
  paying_other_loss: paying transfers out
  paying_other_gain: paying transfers in
  a1p_other_gain: new applications transferred in
  a1p_other_loss: new applications transferred out
  a1p_newjoin: new applications (new)
  a1p_rejoin: new applications (rejoin)
  a1p_to_paying: applications started paying
  start_date: start date
  end_date: end date
  annualisedavgcontribution: estimated annual contribution
  contributors: unique contributors
  stopped_start_count: stopped paying at start date 
  stopped_end_count: stopped paying at end date
  stopped_real_gain: entered stopped paying cycle
  stopped_real_loss: ceased stopped paying
  stopped_other_gain: stopped paying transfers in
  stopped_other_loss: stopped paying transfers out
  stopped_to_paying: left stopped paying cycle (resumed paying)
  stopped_to_other: left stopped paying cycle (exited)
  stopped_unchanged_gain: entered stopped paying cycle (pending resolution)
  a1p_unchanged_gain: new applications (pending payment)
  contactdetail: current contact detail
  followupnotes: follow up notes
  payrollcontactdetail: payroll/hr contact
  lateness: current payment status
  paymenttype: payment type
  paymenttypeid: payment type
  newemployer: current employer
  currentstatus: current status
  newcompany: current site
  paidto: current paid to date
  oldcompanyid: old site
  oldorg: old organiser
  oldemployerid: old employer
  neworg: new organiser
column_descriptions:
  paying_real_net: The number of members whose status became 'paying' during the period minus those that lost the 'paying' status
  paying_end_count: The number of members with the 'paying' status at the end of the period.  '{paying_end_count}' is equal to '{paying_start_count}' plus '{paying_real_gain}' minus '{paying_real_loss}' plus '{paying_other_gain}' minus '{paying_other_loss}'.
  a1p_real_gain: The number of people who became 'awaiting first payment' during the period.  Most of these are new joiners (see '{a1p_newjoin}') but some may have already been members or become 'awaiting first payment' for administrative reasons (see '{a1p_rejoin}') .
  a1p_to_other: The number of 'awaiting first payment' members who were removed from the database during the period.
  paying_start_count: The number of members with the 'paying' status at the beginning of the period.
  paying_real_gain: The number of members whose status become 'paying' during the period.
  paying_real_loss: The number of members whose status ceased to be 'paying' during the period.
  income_net: The amount of money posted against members by support staff during the period (without regard to the period the payment was remitted for).
  contributors: The number of unique members to have contributed dues during the period.
  running_paying_net: The running total of '{paying_real_net}'.  Be careful to sort by the row header then '{period_header}' (the default sort) otherwise this column won't make sense.
  period_header: The intervals dividing '{start_date}' and '{end_date}' as selected by the user.  Beware that if '{start_date}' or '{end_date}' don't align to standard interval boundaries, the first or last interval will be shorter in duration.
  paying_other_gain: The number of paying members gained without involving a member status change and without affecting the union's bottom line.  e.g. transfers of sites between organisers.
  paying_other_loss: The number of paying members lost without involving a member status change and without affecting the union's bottom line.  e.g. transfers of sites between organisers.
  a1p_start_count: The number of members with the 'awaiting first payment' status at the beginning of the period.
  a1p_end_count: The number of members with the 'awaiting first payment' status at the end of the period.
  a1p_newjoin: The number of members who became 'awaiting first payment' during the period who have never been a member before.
  a1p_rejoin: The number of members who became 'awaiting first payment' during the period who have been a member before.
  a1p_to_paying: The number of members who stopped being 'awaiting first payment' during the period because they started paying.
  a1p_other_gain: The number of 'awaiting first payment' members gained without involving a member status change and without affecting the union's bottom line.  e.g. transfers of sites between organisers.
  a1p_other_loss: The number of 'awaiting first payment' members lost without involving a member status change and without affecting the union's bottom line.  e.g. transfers of sites between organisers.
  posted: The amount of money posted to members during the period, including money reposted because of corrections (see '{unposted}').  NB corrections are applied to the period for which they money belongs in order to ensure historical consistency.
  unposted: The amount of money deducted during the period, usually because of undoing a payment.  Be aware that when an undone payment is reposted, the amount will appear in '{posted}'.
  annualisedavgcontribution: The total amount of money posted during the period, divided by the number of unique contributors, scaled to make the period equivalent to a year.  NB If, for any reason, money isn't received for a large portion of members for a large portion of the period, this figure will be low.  e.g.  Members were redistributed (think area changes) or reclassified (think industry changes) mid way through the period.
  stopped_start_count: The number of members with the stopped paying status at the start of the period.
  stopped_end_count: The number of members with the stopped paying status at the end of the period.
  stopped_real_gain: The number of members who changed to the stopped paying status during the period.
  stopped_real_loss: The number of members who changed from the stopped paying status to something else during the period.
  stopped_other_gain: The number of members with the stopped paying status who transfered into this group without changing status.
  stopped_other_loss: The number of members with the stopped paying status who transfered out of this group without changing status.
  stopped_unchanged_gain: The number of members who became stopped paying during the selected period and are still are stopped paying
  a1p_unchanged_gain: The number of members who became awaiting first payment during the selected period and are still are awaiting first payment
  stopped_to_paying: The number of 'stopped paying' members who resumed paying
  stopped_to_other: The number of 'stopped paying' members who got a new status (other than paying) probably due to some follow up process.
  transactions: The number of individual transactions that were posted against members.  A out of pay payment will usually contain numerous transactions.
  lateness: The remittance status of each employer with at least one OOP member attached. The next due date is determined from the '{paidto}' plus the average duration between payments (multipled by the number of unposted payments) plus half this average duration to allow for processing.
  paidto: The date up to which money has been posted.  The employer may have paid past this date but unposted payment don't count toward the '{paidto}' because the '{paidto}' is determined during payment posting.
  paymenttype: Code representing either out of pay, direct debit, credit card or personal (invoice)
  
  
  
  
  
  
  
  
  
  
  
  
  
  
    
  
    
  
    
    
    
  
    
  
  
  
  
        
  
  
  
    
    
  
  
  
  
  
  
