use_new_query_generation_method: true
dimensions:
	0:
	    id: branchid
		name: Branch
		drilldown_target: lead
	1: 
        id: industryid
        name: Industry
		drilldown_target: companyid
	2: 
        id: lead
        name: Lead Organiser
		drilldown_target: companyid
	3: 
        id: org
        name: Organiser
		drilldown_target: companyid
	4: 
        id: areaid
        name: Area
		drilldown_target: companyid
	5: 
        id: companyid
        name: Work Site
		drilldown_target: companyid
	6: 
        id: agreementexpiry
        name: Agreement Expiry
	7: 
        id: del
        name: Delegate Training
		drilldown_target: companyid
	8: 
        id: hsr
        name: HSR Training
		drilldown_target: companyid
	9: 
        id: gender
        name: Gender
	10: 
        id: feegroupid
        name: Fee Group
		drilldown_target: companyid
	11: 
        id: state
        name: State
		drilldown_target: area
	12: 
        id: nuwelectorate
        name: Electorate
		drilldown_target: org
	13: 
        id: statusstaffid
        name: Data Entry
		drilldown_target: companyid
		role_restriction: leader
	14: 
        id: supportstaffid
        name: Support Staff
		drilldown_target: org
	15: 
        id: employerid
        name: Employer
		drilldown_target: companyid
	16: 
        id: hostemployerid
        name: Owner
		drilldown_target: companyid
		role_restriction: admin
	17: 
        id: employmenttypeid
        name: Employment Type
		drilldown_target: companyid
	18: 
        id: paymenttypeid
        name: Payment Type
		drilldown_target: companyid
