email:
  to: 
  from: 
email_errors:
  to: 
  from: 
database:
  host: 
  port: 
  dbname: 
  user: 
  password:
  facttable: 
dimensions:
	0:
	    id: companyid
		name: Company
		drilldown_target: branchid
work_site_dimension_id: companyid